import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from './api.js';
import './styles.css';

const formatMoney = (amount) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format((amount || 0) / 100);
function Login({ onLogin }) {
  const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await onLogin(form.get('email'), form.get('password')); } catch (reason) { setError(reason.message); } };
  return <main className="card"><p className="eyebrow">CREDIT OPERATIONS</p><h1>Welcome to CredOS</h1><p>Manage receivables with confidence.</p><form onSubmit={submit}><label>Email<input name="email" type="email" defaultValue="admin@credos.local" required /></label><label>Password<input name="password" type="password" defaultValue="ChangeMe123!" required /></label>{error && <p className="error">{error}</p>}<button>Sign in</button></form></main>;
}
function App() {
  const [token, setToken] = useState(localStorage.getItem('credos_token'));
  const [data, setData] = useState({ dashboard: null, customers: [], invoices: [], payments: [] }); const [error, setError] = useState('');
  const client = token ? createClient(token) : null;
  const refresh = async () => { try { const [dashboard, customers, invoices, payments] = await Promise.all([client.dashboard(), client.customers(), client.invoices(), client.payments()]); setData({ dashboard, customers, invoices, payments }); setError(''); } catch (reason) { setError(reason.message); } };
  useEffect(() => { if (token) refresh(); }, [token]);
  const login = async (email, password) => { const session = await createClient().login(email, password); localStorage.setItem('credos_token', session.token); setToken(session.token); };
  const create = async (event, action) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await action(values); event.currentTarget.reset(); await refresh(); } catch (reason) { setError(reason.message); } };
  if (!token) return <Login onLogin={login} />;
  const metrics = data.dashboard && [['Outstanding', data.dashboard.receivable], ['Collected', data.dashboard.collected], ['Overdue', data.dashboard.overdue], ['Customers', data.dashboard.customers]];
  const cancel = async (id) => { try { await client.cancelInvoice(id); await refresh(); } catch (reason) { setError(reason.message); } };
  return <main><header><div><p className="eyebrow">CREDIT OPERATIONS</p><h1>Receivables dashboard</h1></div><button className="secondary" onClick={() => { localStorage.removeItem('credos_token'); setToken(null); }}>Sign out</button></header>{error && <p className="error">{error}</p>}<section className="metrics">{metrics?.map(([name, value]) => <article key={name}><small>{name}</small><strong>{name === 'Customers' ? value : formatMoney(value)}</strong></article>)}</section><section className="workspace"><section><h2>Customers</h2><form className="inline" onSubmit={(e) => create(e, (v) => client.createCustomer({ ...v, creditLimit: Number(v.creditLimit) }))}><input name="name" placeholder="Customer name" required /><input name="email" placeholder="Email (optional)" type="email" /><input name="creditLimit" placeholder="Credit limit (paise)" type="number" min="0" defaultValue="0" required /><button>Add customer</button></form><Table headings={['Name', 'Email', 'Credit limit']} rows={data.customers.map((customer) => [customer.name, customer.email || '-', formatMoney(customer.creditLimit)])} /></section><section><h2>Invoices</h2><form className="inline" onSubmit={(e) => create(e, (v) => client.createInvoice({ ...v, total: Number(v.total) }))}><select name="customerId" required defaultValue=""><option value="" disabled>Customer</option>{data.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select><input name="number" placeholder="Invoice number" required /><input name="total" placeholder="Total (paise)" type="number" min="0" required /><input name="dueDate" type="date" required /><button>Issue invoice</button></form><Table headings={['Number', 'Outstanding', 'Due date', '']} rows={data.invoices.map((invoice) => [invoice.number, formatMoney(invoice.outstanding), invoice.dueDate, invoice.status === 'open' ? <button className="text-button" onClick={() => cancel(invoice.id)}>Cancel</button> : invoice.status])} /></section><section><h2>Record payment</h2><form className="inline" onSubmit={(e) => create(e, (v) => client.recordPayment({ ...v, amount: Number(v.amount) }))}><select name="invoiceId" required defaultValue=""><option value="" disabled>Invoice</option>{data.invoices.filter((invoice) => invoice.outstanding > 0).map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.number} - {formatMoney(invoice.outstanding)}</option>)}</select><input name="amount" placeholder="Amount (paise)" type="number" min="1" required /><select name="method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="upi">UPI</option></select><button>Record payment</button></form><Table headings={['Received', 'Method', 'Amount']} rows={data.payments.map((payment) => [new Date(payment.receivedAt).toLocaleDateString(), payment.method, formatMoney(payment.amount)])} /></section></section></main>;
}
function Table({ headings, rows }) { return <div className="table-wrap"><table><thead><tr>{headings.map((heading, index) => <th key={`${heading}-${index}`}>{heading}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((value, column) => <td key={column}>{value}</td>)}</tr>) : <tr><td colSpan={headings.length}>No records yet.</td></tr>}</tbody></table></div>; }
createRoot(document.getElementById('root')).render(<App />);
