import test from 'node:test';
import assert from 'node:assert/strict';
import { CredosService } from '../src/domain.js';

const service = () => { const app = new CredosService({ now: () => new Date('2026-08-05T00:00:00Z') }); const { company } = app.seedAdmin(); return { app, company }; };
test('a payment cannot exceed its invoice outstanding balance', () => { const { app, company } = service(); const customer = app.createCustomer(company.id, { name: 'Aster' }); const invoice = app.issueInvoice(company.id, { customerId: customer.id, total: 10000, dueDate: '2026-08-10' }); assert.throws(() => app.recordPayment(company.id, { invoiceId: invoice.id, amount: 10001 }), /outstanding/); });
test('payment allocation updates invoice and dashboard totals', () => { const { app, company } = service(); const customer = app.createCustomer(company.id, { name: 'Aster' }); const invoice = app.issueInvoice(company.id, { customerId: customer.id, total: 10000, dueDate: '2026-08-10' }); const result = app.recordPayment(company.id, { invoiceId: invoice.id, amount: 4000 }); assert.equal(result.invoice.outstanding, 6000); assert.deepEqual(app.dashboard(company.id), { customers: 1, invoices: 1, receivable: 6000, collected: 4000, overdue: 0 }); });
test('a company cannot invoice another company customer', () => { const { app, company } = service(); const other = app.createCompany({ name: 'Other' }); const customer = app.createCustomer(company.id, { name: 'Private customer' }); assert.throws(() => app.issueInvoice(other.id, { customerId: customer.id, total: 1, dueDate: '2026-08-10' }), /customer not found/); });
test('only an owner can provision a company user', () => { const { app, company } = service(); const { user: owner } = app.seedAdmin({ email: 'second@credos.local' }); const operator = app.createUser(owner, { name: 'Collector', email: 'collector@credos.local', password: 'safe-password', role: 'operator' }); assert.equal(operator.companyId, owner.companyId); assert.throws(() => app.createUser({ ...operator, companyId: company.id }, { name: 'Blocked', email: 'blocked@credos.local', password: 'safe-password' }), /insufficient permission/); });
test('password verification rejects an incorrect password', () => { const { app } = service(); app.seedAdmin({ email: 'login@credos.local', password: 'secret' }); assert.throws(() => app.authenticate('login@credos.local', 'wrong'), /invalid email or password/); });
test('a customer credit limit includes unpaid invoices', () => { const { app, company } = service(); const customer = app.createCustomer(company.id, { name: 'Limited', creditLimit: 10000 }); app.issueInvoice(company.id, { customerId: customer.id, number: 'INV-1', total: 8000, dueDate: '2026-08-10' }); assert.throws(() => app.issueInvoice(company.id, { customerId: customer.id, number: 'INV-2', total: 2001, dueDate: '2026-08-10' }), /credit limit/); });
test('invoice numbers are unique per company', () => { const { app, company } = service(); const customer = app.createCustomer(company.id, { name: 'Numbered' }); app.issueInvoice(company.id, { customerId: customer.id, number: 'DUP-1', total: 1, dueDate: '2026-08-10' }); assert.throws(() => app.issueInvoice(company.id, { customerId: customer.id, number: 'DUP-1', total: 1, dueDate: '2026-08-10' }), /already exists/); });
test('an unpaid invoice can be cancelled and is removed from receivables', () => { const { app, company } = service(); const { user } = app.seedAdmin({ email: 'owner@example.com' }); const customer = app.createCustomer(user.companyId, { name: 'Cancelled' }); const invoice = app.issueInvoice(user.companyId, { customerId: customer.id, number: 'CANCEL-1', total: 100, dueDate: '2026-08-01' }); assert.equal(app.cancelInvoice(user, invoice.id).status, 'cancelled'); assert.equal(app.dashboard(user.companyId).receivable, 0); assert.throws(() => app.recordPayment(user.companyId, { invoiceId: invoice.id, amount: 1 }), /cancelled/); });
